# Site settings
title: invrse - blog de desenvolvimento de jogos
email: ottorobba@gmail.com
author: Otto Robba
description: "Blog educacional voltado para o desenvolvimento de jogos, incluindo design, programação, ferramentas, técnicas de trabalho e produção."
baseurl: ""
url: "http://invrse.com.br"
google_analytics: UA-55865997-1
animated: false

# Build settings
markdown: kramdown
permalink: pretty
#paginate: 3
sass:
  compressed: true

gems: [jekyll-sitemap]
